name: "building_permit_scraper"
version: "1.0.0"
config-version: 2

profile: "building_permit_scraper"

model-paths: ["models"]
seed-paths: ["seeds"]
clean-targets: ["target", "dbt_packages"]

models:
  building_permit_scraper:
    staging:
      +materialized: view
    marts:
      +materialized: table
